### ISSUE TITLE
AppData path in Core.Config is readonly

### ISSUE THREAD

**Issue by ftrueck** [ezet/evelib#41]
It is not possible to change the AppData Path in Config, therefore the lib will not run on webservers.
It would be better design, to implement a property with a setter which will reinitialise the inherited paths on change.

**Comment by ezet** [comment]
Use the project configuration file. It's App.config for desktop, Web has a similar but differently named file that serves the same purpose.

**Comment by ezet** [comment]
Relevant settings are 
  <appSettings>
    
    <add key="eveLib.AppData" value="EveLib" />
    
    <add key="eveLib.UserAgent" value="EveLib-development" />
</appSettings>

**Comment by ftrueck** [comment]
This will not work because of this: 

public static readonly string AppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) +
                                                Separator;



This will set AppData to "\" which will result in "\EveLib\Cache" as you can see here:

string appName = ConfigurationManager.AppSettings["eveLib.AppData"];
            AppData += !string.IsNullOrEmpty(appName) ? appName : "EveLib";
            CachePath = AppData + Separator + "Cache";

So the web application will try to access the wrong path (\EveLib\Cache\) which results in an .NET Exception.

The correct way would be: Server.MapPath(CachePath);
Then .net will make this: C:\Inetpub\wwwroot\<webapp>\EveLib\Cache

Because Server.MapPath will not work in Desktop Environments it would be the best way to Provide AppPath Field as Property:

private static string _appData;
        public static string AppData
        {
            get
            {
                if (String.IsNullOrWhiteSpace(_appData))
                {
                    _appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + Separator;
                }
                return _appData;
            }

            set
            {
                _appData = value;
                SetConfig();
            }
        }

static Config() {
            SetConfig();
        }

        private static void SetConfig()
        {
            if (String.IsNullOrEmpty(UserAgent))
                UserAgent = "EveLib";
            CachePath = AppData + Separator + "Cache";
            ImagePath = AppData + Separator + "Images";
            CacheRegister = CachePath + Separator + CacheRegisterFileName;
        }

For me this works but there may be better ways. I leave this up to you guys. :)

**Comment by ezet** [comment]
Fixed.

**Comment by Joeeigel** [comment]
I'm still having this issue, looking through all remote branches this file hasn't been updated in over a year. 

It may just be myself doing something wrong however and the fix _has_ been applied somewhere

**Comment by ezet** [comment]
I'll have a look tomorrow and Sunday. Could you help me test it later?

**Comment by Joeeigel** [comment]
Would be more than happy to, I'm using a version where I've just forced it to use Server.MapPath(); for now as I know the environment my code will be ran on, but I don't mind switching it our to see if we can get this solved.

**Comment by ezet** [comment]
Does the most recent commit to the dev branch work for you? Set
Config.AppData before instantiating EveCrest.

**Comment by Joeeigel** [comment]
Still an issue, full  stacktrace below:

`Could not find a part of the path '\\Cache\EveXml'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.DirectoryNotFoundException: Could not find a part of the path '\\Cache\EveXml'.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[DirectoryNotFoundException: Could not find a part of the path '\\Cache\EveXml'.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +519
   System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost) +11960522
   System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost) +64
   System.IO.Directory.CreateDirectory(String path) +33
   eZet.EveLib.Core.Cache.<StoreAsync>d__14.MoveNext() in C:\Dev\Eve\evelib-EveAuth_v3.0.1\evelib-EveAuth_v3.0.1\EveLib.Core\Cache\EveLibFileCache.cs:65
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) +25
   eZet.EveLib.EveXmlModule.RequestHandlers.<RequestAsync>d__13`1.MoveNext() in C:\Dev\Eve\evelib-EveAuth_v3.0.1\evelib-EveAuth_v3.0.1\EveLib.EveXml\RequestHandlers\EveXmlRequestHandler.cs:68
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   eZet.EveLib.EveXmlModule.<ensureInitialized>d__30.MoveNext() in C:\Dev\Eve\evelib-EveAuth_v3.0.1\evelib-EveAuth_v3.0.1\EveLib.EveXml\ApiKey.cs:166`

**Comment by ezet** [comment]
That makes no sense. You used this commit?
166766a37387e23c269359a4de809af831feb700
You made sure to change that before instantiating the EveXml object? Can
you check the AppData, CachePath and ImagePath properties after you set it ?

**Comment by ezet** [comment]
Could you please confirm that it still does not work for you ?

**Comment by Joeeigel** [comment]
Issue was with my end, not the lib itself.

And by my end, I mean me.

Sorry for your time <3

**Comment by ezet** [comment]
Fixed.
